extra_messages = {"You are standing {wvery close to the the bridge's western foundation{n. If you go west you will be back on solid ground ...",
                       "The bridge slopes precariously where it extends eastwards towards the lowest point - the center point of the hang bridge.",
                       "You are {whalfways{n out on the unstable bridge.",
                       "The bridge slopes precariously where it extends westwards towards the lowest point - the center point of the hang bridge.",
                       "You are standing {wvery close to the bridge's eastern foundation{n. If you go east you will be back on solid ground ...",
                "The bridge sways in the wind.", "The hanging bridge creaks dangerously.",
                "You clasp the ropes firmly as the bridge sways and creaks under you.",
                "From the castle you hear a distant howling sound, like that of a large dog or other beast.",
                "The bridge creaks under your feet. Those planks does not seem very sturdy.",
                "Far below you the ocean roars and throws its waves against the cliff, as if trying its best to reach you.",
                "Parts of the bridge come loose behind you, falling into the chasm far below!",
                "A gust of wind causes the bridge to sway precariously.",
                "Under your feet a plank comes loose, tumbling down. For a moment you dangle over the abyss ...",
                "The section of rope you hold onto crumble in your hands, parts of it breaking apart. You sway trying to regain balance.",
               "Suddenly the plank you stand on gives way under your feet! You fall!",
               "\nYou try to grab hold of an adjoining plank, but all you manage to do is to ",
               "divert your fall westwards, towards the cliff face. This is going to hurt ... ",
               "\n ... The world goes dark ...\n\n",
               "It is pitch black. You are likely to be eaten by a grue.",
                 "It's pitch black. You fumble around but cannot find anything.",
                 "You don't see a thing. You feel around, managing to bump your fingers hard against something. Ouch!",
                 "You don't see a thing! Blindly grasping the air around you, you find nothing.",
                 "It's totally dark here. You almost stumble over some un-evenness in the ground.",
                 "You are completely blind. For a moment you think you hear someone breathing nearby ... \n ... surely you must be mistaken.",
                 "Blind, you think you find some sort of object on the ground, but it turns out to be just a stone.",
                 "Blind, you bump into a wall. The wall seems to be covered with some sort of vegetation, but its too damp to burn.",
                 "You can't see anything, but the air is damp. It feels like you are far underground.",
                "You don't want to stumble around in blindness anymore. You already ",
                      "found what you need. Let's get light already!",
                "Your fingers bump against a splinter of wood in a corner. It smells of resin and seems dry enough to burn! ",
                    "You pick it up, holding it firmly. Now you just need to {wlight{n it using the flint and steel you carry with you."}

