#!/bin/bash

#Usage : ./run_cpu <game_num>
#game_num is 1, 2, 3 ...

# exp_folder="logs/tutorial_lstm_priority5_tiedAO_hist1/"
# exp_folder="logs/lstm3_rmsprop/"
exp_folder="logs/lstm_rmsprop_tut2/"
#exp_folder="logs/lstm_rmsprop_tut3/"
mkdir -p $exp_folder;

FRAMEWORK="alewrap"
STEP_SIZE=5000 #step size for learn_start, eval, saving, etc.
hist_len=1
max_steps=250 #max steps  in a single episode
minibatch_size=64
quest_levels=1
game_num=$1
game_path=$PWD"/roms/"
env_params="useRGB=true"
agent="NeuralQLearner"
n_replay=1
tutorial_world=1
random_test=0

recurrent=1
# netfile="\"bow_embedding\"" 
# netfile="\"rnn_embedding\""  
netfile="\"lstm_embedding\""  
# netfile="\"logs/DQN3_0_1__FULL_Y.t7\""
# netfile="\"logs/lstm_rmsprop/DQN3_0_1_3_FULL_Y.t7\""
# netfile="\"logs/bow_rmsprop/DQN3_0_1_4_FULL_Y.t7\""

update_freq=4
actrep=1
discount=0.5
seed=1
learn_start=$STEP_SIZE
pool_frms_type="\"max\""
pool_frms_size=2
initial_priority="false"
replay_memory=100000
eps=1
eps_end=0.2
# eps_endt=replay_memory
eps_endt=200000
lr=0.0005

agent_type=$exp_folder"DQN3_0_1"
agent_name=$agent_type"_"$1"_FULL_Y"
state_dim=300
ncols=1
agent_params="lr="$lr",ep="$eps",ep_end="$eps_end",ep_endt="$eps_endt",discount="$discount",hist_len="$hist_len",learn_start="$learn_start",replay_memory="$replay_memory",update_freq="$update_freq",n_replay="$n_replay",network="$netfile",state_dim="$state_dim",minibatch_size="$minibatch_size",rescale_r=1,ncols="$ncols",bufferSize=512,valid_size=500,target_q="$STEP_SIZE",clip_delta=1,min_reward=-1,max_reward=10"
steps=2000000
eval_freq=$STEP_SIZE
eval_steps=$STEP_SIZE
prog_freq=$STEP_SIZE
save_freq=$STEP_SIZE
gpu=-1
random_starts=30
pool_frms="type="$pool_frms_type",size="$pool_frms_size
num_threads=1

args="-framework $FRAMEWORK -recurrent $recurrent -game_path $game_path -name $agent_name -env_params $env_params -agent $agent -agent_params $agent_params -steps $steps -eval_freq $eval_freq -eval_steps $eval_steps -prog_freq $prog_freq -save_freq $save_freq -actrep $actrep -gpu $gpu -random_starts $random_starts -pool_frms $pool_frms -seed $seed -threads $num_threads"
echo $args

th agent.lua $args -saveNetworkParams -exp_folder $exp_folder  -game_num $game_num -quest_levels $quest_levels -state_dim  $state_dim -max_steps $max_steps -tutorial_world $tutorial_world -random_test $random_test;
